"""test.

Revision ID: 48991c867df9
Revises: 99f417f99dda
Create Date: 2021-11-15 15:31:50.276886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48991c867df9'
down_revision = '99f417f99dda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('user_token', sa.String(), nullable=False))
    op.drop_constraint('character_owner_fkey', 'character', type_='foreignkey')
    op.create_foreign_key(None, 'character', 'user', ['user_token'], ['token'])
    op.drop_column('character', 'owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('owner', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'character', type_='foreignkey')
    op.create_foreign_key('character_owner_fkey', 'character', 'user', ['owner'], ['token'])
    op.drop_column('character', 'user_token')
    # ### end Alembic commands ###
